basePath: /api
definitions:
  auth.TokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  common.Response:
    properties:
      data: {}
      message:
        type: string
    type: object
  dtos.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  dtos.RegisterRequest:
    properties:
      bio:
        type: string
      display_name:
        type: string
      email:
        type: string
      password:
        type: string
      profile_picture_url:
        type: string
      registration_date:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - display_name
    - email
    - password
    - username
    type: object
host: localhost:8000
info:
  contact:
    email: fajarsuryahidayad@gmail.com
    name: API Support
  description: An Article API for WAOW homework.
  title: WAOW Article API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user, returns accessToken and RefreshToken
      parameters:
      - description: Login User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.LoginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/auth.TokenResponse'
      summary: Sign in user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user and returns user ID
      parameters:
      - description: User Registration
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dtos.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/common.Response'
      summary: Register a new user
      tags:
      - auth
securityDefinitions:
  JWT Auth:
    type: basic
  JWT Bearer Auth:
    description: Bearer Token
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
